# PYTHON LAB EXERCISE 9 


### Write a program to distinguish between Array Indexing and Fancy Indexing.

In [2]:
import numpy as np


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


element_1 = arr[0, 0]  
row_slice = arr[1, :]  
column_slice = arr[:, 2]  

print("ARRAY INDEXING :")
print("ELEMENTS AT  [0, 0]:", element_1)
print("SECOND ROW ", row_slice)
print("THIRD COLUMN :", column_slice)


row_indices = np.array([0, 2]) 
fancy_row = arr[row_indices, :]  

column_indices = np.array([0, 2]) 
fancy_column = arr[:, column_indices]  

boolean_mask = arr > 4  
fancy_boolean = arr[boolean_mask]  

print("\nFANCY INDEXING :")
print("ROWS 0 AND 2 :", fancy_row)
print("COLUMNS 0 AND 2 :\n", fancy_column)
print("ELEMENTS > 4:", fancy_boolean)


ARRAY INDEXING :
ELEMENTS AT  [0, 0]: 1
SECOND ROW  [4 5 6]
THIRD COLUMN : [3 6 9]

FANCY INDEXING :
ROWS 0 AND 2 : [[1 2 3]
 [7 8 9]]
COLUMNS 0 AND 2 :
 [[1 3]
 [4 6]
 [7 9]]
ELEMENTS > 4: [5 6 7 8 9]


### Array 2D - slicing 

In [1]:
import numpy as np


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])


slice_1 = arr[0:2, 1:3]  
slice_2 = arr[:, 2:]     
slice_3 = arr[1, :]   
slice_4 = arr[:, 1]   

print("ORIGINAL ARRAY :")
print(arr)

print("\nSLICED ARRAY 1 ->  (ROWS 0 to 1, COLUMNS 1 to 2):")
print(slice_1)

print("\nSLICED ARRAY  2 (ALL ROWS, COLUMNS 2 AND BEYOND ):")
print(slice_2)

print("\nSLICED ARRAY 3 (ROW 1, ALL COLUMNS):")
print(slice_3)

print("\nSLICED ARRAY  4 (ALL ROWS, COLUMN 1):")
print(slice_4)


ORIGINAL ARRAY :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

SLICED ARRAY 1 ->  (ROWS 0 to 1, COLUMNS 1 to 2):
[[2 3]
 [6 7]]

SLICED ARRAY  2 (ALL ROWS, COLUMNS 2 AND BEYOND ):
[[ 3  4]
 [ 7  8]
 [11 12]]

SLICED ARRAY 3 (ROW 1, ALL COLUMNS):
[5 6 7 8]

SLICED ARRAY  4 (ALL ROWS, COLUMN 1):
[ 2  6 10]


### Create the 5-Dimensional arrays using ‘ndmin’.

In [2]:
import numpy as np


arr_5d = np.array([1, 2, 3], ndmin=5)
print("5-DIMENSIONAL ARRAY :")
print(arr_5d)
print("SHAPE OF 5 DIEMSIONAL ARRAY :", arr_5d.shape)


5-DIMENSIONAL ARRAY :
[[[[[1 2 3]]]]]
SHAPE OF 5 DIEMSIONAL ARRAY : (1, 1, 1, 1, 3)


### Reshape the array from 1-D to 2-D array.

In [3]:
import numpy as np


arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, 3)

print("ORIGINAL 1-D ARRAY :")
print(arr_1d)
print("RESHAPED 2-D ARRAY :")
print(arr_2d)


ORIGINAL 1-D ARRAY :
[1 2 3 4 5 6]
RESHAPED 2-D ARRAY :
[[1 2 3]
 [4 5 6]]


### Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstacked = np.hstack((arr1, arr2))
print("HORIZONTALLY STACKED :")
print(hstacked)

vstacked = np.vstack((arr1, arr2))
print("VERTICALLY STACKED :")
print(vstacked)

dstacked = np.dstack((arr1, arr2))
print("DEPTH WISE STACKED :")
print(dstacked)

HORIZONTALLY STACKED :
[1 2 3 4 5 6]
VERTICALLY STACKED :
[[1 2 3]
 [4 5 6]]
DEPTH WISE STACKED :
[[[1 4]
  [2 5]
  [3 6]]]


### Perform the searchsort method in Numpy array.

In [6]:
import numpy as np

arr = np.array([3, 1, 2, 4, 5])
sorted_arr = np.sort(arr)
print("SORTED ARRAY IS :", sorted_arr)


Sorted Array: [1 2 3 4 5]


### Create Numpy Structured array using your domain features.

In [7]:
import numpy as np


dtype = [('name', 'U10'), ('age', int), ('userId', int), ('userAccountType', bool)]

# Create a structured array with sample data
data = [('hello@suvajit_k', 21, 2347261, True), ('hello@subham_g', 21, 2547814, False), ('hello@chowdhury_a', 22, 7784524, True)]
structured_array = np.array(data, dtype=dtype)

# Accessing elements by field name
print("NAME :", structured_array['name'])
print("AGE :", structured_array['age'])
print("USERID :", structured_array['userId'])
print("ACCOUNT TYPE :", structured_array['userAccountType'])


NAME : ['hello@suva' 'hello@subh' 'hello@chow']
AGE : [21 21 22]
USERID : [2347261 2547814 7784524]
ACCOUNT TYPE : [ True False  True]


### Create Data frame using List and Dictionary.

In [9]:
import pandas as pd

# Creating a DataFrame using a dictionary
data = {
    "Name": ["subham", "hrishabh", "mano"],
    "Age": [25, 30, 22]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22


In [10]:
import pandas as pd

# Creating a DataFrame using lists
data = [
    ["salini", 25],
    ["subham", 30],
    ["david", 22]
]

# Define column names
columns = ["Name", "Age"]

# Create a DataFrame
df = pd.DataFrame(data, columns=columns)

# Display the DataFrame
print(df)


     Name  Age
0  salini   25
1  subham   30
2   david   22


### Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [11]:
import pandas as pd
import numpy as np

# Create a sample DataFrame with missing data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Ella'],
    'Age': [25, np.nan, 22, 30, 35],
    'Salary': [45000, 55000, np.nan, np.nan, 60000]
}

df = pd.DataFrame(data)

# Check for missing data using isnull()
print("Check for missing data using isnull():")
print(df.isnull())

# Check for non-missing data using notnull()
print("\nCheck for non-missing data using notnull():")
print(df.notnull())

# Drop rows with missing data using dropna()
df_dropped = df.dropna()
print("\nDataFrame after dropping rows with missing data:")
print(df_dropped)

# Fill missing data with a specific value using fillna()
df_filled = df.fillna({'Age': df['Age'].mean(), 'Salary': df['Salary'].median()})
print("\nDataFrame after filling missing data:")
print(df_filled)

# Replace missing values with a specific value using replace()
df_replaced = df.replace(np.nan, 0)
print("\nDataFrame after replacing missing data:")
print(df_replaced)

# Interpolate missing values using interpolate()
df_interpolated = df.interpolate()
print("\nDataFrame after interpolating missing data:")
print(df_interpolated)


Check for missing data using isnull():
    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False    True
4  False  False   False

Check for non-missing data using notnull():
   Name    Age  Salary
0  True   True    True
1  True  False    True
2  True   True   False
3  True   True   False
4  True   True    True

DataFrame after dropping rows with missing data:
    Name   Age   Salary
0  Alice  25.0  45000.0
4   Ella  35.0  60000.0

DataFrame after filling missing data:
      Name   Age   Salary
0    Alice  25.0  45000.0
1      Bob  28.0  55000.0
2  Charlie  22.0  55000.0
3    David  30.0  55000.0
4     Ella  35.0  60000.0

DataFrame after replacing missing data:
      Name   Age   Salary
0    Alice  25.0  45000.0
1      Bob   0.0  55000.0
2  Charlie  22.0      0.0
3    David  30.0      0.0
4     Ella  35.0  60000.0

DataFrame after interpolating missing data:
      Name   Age        Salary
0    Alice  25.0  45000.000000
1      Bob  2

/tmp/ipykernel_6036/3908641328.py:37: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


### Perform the Hierarchical Indexing in the above created dataset.

In [12]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Ella'],
    'Age': [25, np.nan, 22, 30, 35],
    'Salary': [45000, 55000, np.nan, np.nan, 60000]
}

df = pd.DataFrame(data)

# Set hierarchical indexing using set_index()
df.set_index(['Name', 'Age'], inplace=True)

# Display the DataFrame with hierarchical indexing
print(df)


               Salary
Name    Age          
Alice   25.0  45000.0
Bob     NaN   55000.0
Charlie 22.0      NaN
David   30.0      NaN
Ella    35.0  60000.0
